algorithm: fixmatch_multihead
net: wrn_multihead_28_2

# optimization configs
epoch: 20
num_train_iter: 1000000
num_eval_iter: 1000000
num_log_iter: 50
optim: AdamW
lr: 0.0005
layer_decay: 0.5
batch_size: 8
eval_batch_size: 8

# dataset configs
dataset: disaster
task: humanitarian
num_labels: 0
crop_ratio: 0.875
train_filename: train_eda.jsonl
dev_filename: dev_eda.jsonl
test_filename: test_eda.jsonl
unlabeled_filename: unlabeled_eda.jsonl
data_dir: /export/home/acs/stud/r/robert.popovici/licenta/datasets/humanitarian
img_dir: /export/home/acs/stud/r/robert.popovici/licenta/datasets

# algorithm specific configs
hard_label: True
uratio: 3
ulb_loss_ratio: 1.0

# device configs
gpu: 0
world_size: 1
num_workers: 2
distributed: False

# test configs
resume: True
save_dir: ./saved_models/humanitarian/fixmatch/eval
save_name: fixmatch-multihead
load_path: ./saved_models/humanitarian/fixmatch/train/fixmatch-multihead/model_best.pth
eval_only: True
