import torch
from semilearn.core.hooks import Hook
from collections import Counter

from enum import Enum
class MultiheadAgreementTypes(Enum):
    LowConfDisagreement = 1
    HighConfDisagreement = 2
    DiffConfDisagreement = 3
    LowConfAgreement = 4
    HighConfAgreement = 5
    UnkConfAgreement = 6
    NA = 7
    DiffConfAgreement = 8

def check_apm_agreement_v9(value):
    if value in [MultiheadAgreementTypes.HighConfAgreement, MultiheadAgreementTypes.UnkConfAgreement]:
        return 1 # agreement with valid pseudo-label
    elif value in [MultiheadAgreementTypes.DiffConfDisagreement, MultiheadAgreementTypes.DiffConfAgreement, MultiheadAgreementTypes.LowConfAgreement]:
        return 0 # disagreement with valid pseudo-label
    elif value in [MultiheadAgreementTypes.LowConfDisagreement, MultiheadAgreementTypes.HighConfDisagreement, MultiheadAgreementTypes.NA]:
        return -1 # no valid pseudo-label
    else:
        raise ValueError(f'{value} is not a valid MultiheadAgreementTypes.')

def check_apm_agreement_v3(value):
    if value in [MultiheadAgreementTypes.HighConfAgreement, MultiheadAgreementTypes.UnkConfAgreement]:
        return 1 # agreement with valid pseudo-label
    elif value in [MultiheadAgreementTypes.DiffConfDisagreement, MultiheadAgreementTypes.DiffConfAgreement]:
        return 0 # disagreement with valid pseudo-label
    elif value in [MultiheadAgreementTypes.LowConfDisagreement, MultiheadAgreementTypes.HighConfDisagreement, MultiheadAgreementTypes.LowConfAgreement, MultiheadAgreementTypes.NA]:
        return -1 # no valid pseudo-label
    else:
        raise ValueError(f'{value} is not a valid MultiheadAgreementTypes.')

def check_apm_agreement_orig(value):
    if value in [MultiheadAgreementTypes.HighConfAgreement, MultiheadAgreementTypes.DiffConfAgreement, MultiheadAgreementTypes.UnkConfAgreement]:
        return 1 # agreement with valid pseudo-label
    elif value in [MultiheadAgreementTypes.DiffConfDisagreement]:
        return 0 # disagreement with valid pseudo-label
    elif value in [MultiheadAgreementTypes.LowConfDisagreement, MultiheadAgreementTypes.HighConfDisagreement, MultiheadAgreementTypes.LowConfAgreement, MultiheadAgreementTypes.NA]:
        return -1 # no valid pseudo-label
    else:
        raise ValueError(f'{value} is not a valid MultiheadAgreementTypes.')

class MultiMatchHook(Hook):
    def __init__(self, args, apm_log_hook) -> None:
        super().__init__()

        self.args = args
        self.apm_log_hook = apm_log_hook

        self.num_heads = args.num_heads
        self.num_classes = args.num_classes
        self.ulb_dest_len = args.ulb_dest_len

        self.smoothness = args.smoothness
        self.apm_percentile = args.apm_percentile
        self.apm = torch.zeros((self.num_heads, self.ulb_dest_len, self.num_classes)).to(args.device)

        # apm_cutoff[head_id][class_id] = APM threshold for class_id when head_id is excluded
        self.apm_cutoff = torch.zeros((self.num_heads, self.num_classes)).to(args.device)

        # predictions for weakly augmented data for each head (head pseudolabels)
        self.weak_labels = torch.ones((self.num_heads, self.ulb_dest_len)).to(args.device) * -1

        # weak labels that exceed APM threshold for agreement
        self.weak_agreement_mask = torch.zeros((self.num_heads, self.ulb_dest_len), dtype=torch.bool).to(args.device)

        # predictions for strongly augmented data for each head
        self.strong_labels = torch.ones((self.num_heads, self.ulb_dest_len), dtype=torch.int64).to(args.device) * -1

        # labels generated by APM values, where heads didn't reach an agreement
        self.apm_labels = torch.ones((self.num_heads, self.ulb_dest_len), dtype=torch.int).to(args.device) * -1

        # MultiheadAgreementTypes
        self.agreement_types = torch.zeros((self.num_heads, self.ulb_dest_len), dtype=torch.int).to(args.device)

    def update(self, algorithm, logits_x_ulb_w, logits_x_ulb_s, idx_ulb, head_id):
        epoch = algorithm.epoch
        
        max_probs, pseudo_labels = torch.topk(logits_x_ulb_w, 2)
        for i, idx in enumerate(idx_ulb.tolist()):
            pm = logits_x_ulb_w[i] - max_probs[i][0]
            pm[pseudo_labels[i][0]] = max_probs[i][0] - max_probs[i][1]

            if self.args.apm_update_method == 'original':
                self.apm[head_id][idx] = pm * self.smoothness / (1 + epoch) + self.apm[head_id][idx] * (1 - self.smoothness / (1 + epoch))
            elif self.args.apm_update_method == 'ema':
                self.apm[head_id][idx] = pm * (1 - self.smoothness) + self.apm[head_id][idx] * self.smoothness
            else:
                raise NotImplementedError()

            self.weak_labels[head_id][idx] = pseudo_labels[i][0]

        self.strong_labels[head_id][idx_ulb] = torch.max(logits_x_ulb_s, dim=-1)[1]

    def get_apm_label_v2(self, algorithm, idx, label1, label2, head_id, head_id1, head_id2):
        self.weak_agreement_mask[head_id][idx] = False
        
        if self.args.multihead_apm_variant in ['v3', 'v4', 'v5', 'v6', 'v8', 'v4-cutoff']:
            check_apm_agreement = check_apm_agreement_v3
        elif self.args.multihead_apm_variant in ['v9']:
            check_apm_agreement = check_apm_agreement_v9
        else:
            assert self.args.multihead_apm_variant == 'original'
            check_apm_agreement = check_apm_agreement_orig

        # We don't have default apm_cutoff values for the first epoch
        if algorithm.epoch == 0 and self.args.multihead_apm_variant not in ['v5', 'v6', 'v9']:
            _multihead_agreement_type = MultiheadAgreementTypes.NA
            self.agreement_types[head_id][idx] = _multihead_agreement_type.value
            return -1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
    
        apm_pass1 = self.apm[head_id1][idx][label1] >= self.apm_cutoff[head_id][label1]
        apm_pass2 = self.apm[head_id2][idx][label2] >= self.apm_cutoff[head_id][label2]

        if label1 == label2:
            # No need to check APM for agreement
            if not self.args.use_agreement_apm:
                self.weak_agreement_mask[head_id][idx] = True
                _multihead_agreement_type = MultiheadAgreementTypes.UnkConfAgreement
                self.agreement_types[head_id][idx] = _multihead_agreement_type.value
                return label1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
            
            # At least one head APM needs to exceed threshold
            if apm_pass1 and apm_pass2:
                self.weak_agreement_mask[head_id][idx] = True
                _multihead_agreement_type = MultiheadAgreementTypes.HighConfAgreement
                self.agreement_types[head_id][idx] = _multihead_agreement_type.value
                return label1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
            
            if apm_pass1 or apm_pass2:
                self.weak_agreement_mask[head_id][idx] = True
                _multihead_agreement_type = MultiheadAgreementTypes.DiffConfAgreement
                self.agreement_types[head_id][idx] = _multihead_agreement_type.value
                return label1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
            
            _multihead_agreement_type = MultiheadAgreementTypes.LowConfAgreement
            self.agreement_types[head_id][idx] = _multihead_agreement_type.value
            return -1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)

        
        # Both labels exceed the thresholds => We don't know what to choose, so ignore
        if apm_pass1 and apm_pass2:
            _multihead_agreement_type = MultiheadAgreementTypes.HighConfDisagreement
            self.agreement_types[head_id][idx] = _multihead_agreement_type.value
            return -1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
        
        if apm_pass1:
            _multihead_agreement_type = MultiheadAgreementTypes.DiffConfDisagreement
            self.agreement_types[head_id][idx] = _multihead_agreement_type.value
            self.apm_labels[head_id][idx] = label1
            return label1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
        
        if apm_pass2:
            _multihead_agreement_type = MultiheadAgreementTypes.DiffConfDisagreement
            self.agreement_types[head_id][idx] = _multihead_agreement_type.value
            self.apm_labels[head_id][idx] = label2
            return label2, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)
        
        # Neither of the 2 labels has passed the threshold
        _multihead_agreement_type = MultiheadAgreementTypes.LowConfDisagreement
        self.agreement_types[head_id][idx] = _multihead_agreement_type.value
        return -1, _multihead_agreement_type.value, check_apm_agreement(_multihead_agreement_type)

    # @overrides
    def after_train_step(self, algorithm):
        # if self.every_n_iters(algorithm, algorithm.num_eval_iter) or self.is_last_iter(algorithm):

        if (self.args.num_recalibrate_iter > 0 and self.every_n_iters(algorithm, self.args.num_recalibrate_iter)) \
            or (self.args.num_recalibrate_iter == 0 and self.end_of_epoch(algorithm)):

            algorithm.print_fn("Recomputing apm_cutoff...")

            for head_id, head_id1, head_id2 in [(0, 1, 2), (1, 0, 2), (2, 0, 1)]:
                if self.args.multihead_apm_variant == 'v4-cutoff':
                    break
                if self.args.multihead_apm_variant in ['v6', 'v8', 'v9']:
                    values = []
                    apm_sets = []
                    for label in range(self.num_classes):
                        mask = self.weak_labels[head_id1] == self.weak_labels[head_id2]
                        mask = mask & (self.weak_labels[head_id1] == label)
                        if 1 not in mask:
                            values.append(0)
                            apm_sets.append(None)
                            continue
                        apm_set1 = self.apm[head_id1][mask]
                        apm_set2 = self.apm[head_id2][mask]
                        apm_set = torch.cat((apm_set1[:, label], apm_set2[:, label]), dim=0).float()
                        perc = (apm_set < 0).float().mean()
                        values.append(perc)
                        apm_sets.append(apm_set)
                    perc = max(values)
                    print(f'Computed percentile: {perc}')
                    for label in range(self.num_classes):
                        if apm_sets[label] is None:
                            self.apm_cutoff[head_id][label] = 0
                        else:
                            self.apm_cutoff[head_id][label] = torch.quantile(apm_sets[label], perc)

                else:
                    for label in range(self.num_classes):
                        # Both heads need to choose the selected label
                        mask = self.weak_labels[head_id1] == self.weak_labels[head_id2]
                        mask = mask & (self.weak_labels[head_id1] == label)

                        # Nothing was found => Use 0 as apm_cutoff
                        if 1 not in mask:
                            self.apm_cutoff[head_id][label] = 0
                            break
                        
                        # Merge apm values for head1 and head2 for the current label
                        apm_set1 = self.apm[head_id1][mask]
                        apm_set2 = self.apm[head_id2][mask]
                        apm_set = torch.cat((apm_set1[:, label], apm_set2[:, label]), dim=0)

                        # Use apm_percentile as the new threshold
                        if self.args.no_low:
                            self.apm_cutoff[head_id][label] = torch.quantile(apm_set.float(), self.apm_percentile)
                        else:
                            self.apm_cutoff[head_id][label] = max(0, torch.quantile(apm_set.float(), self.apm_percentile))


            self.apm_log_hook.after_train_epoch(algorithm)

            # reset all APM labels to -1
            self.apm_labels = torch.ones((self.num_heads, self.ulb_dest_len), dtype=torch.int).to(self.args.device) * -1

            self.agreement_types = torch.zeros((self.num_heads, self.ulb_dest_len), dtype=torch.int).to(self.args.device)

