algorithm: multimatch
save_dir: ./saved_models/usb_llm_safety/multimatch
save_name: multimatch_aegis2.0_wildguard_RH
resume: True
load_path: ./saved_models/usb_llm_safety/multimatch/multimatch_aegis2.0_wildguard_RH/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 56200
num_warmup_iter: 562
num_log_iter: 140
num_eval_iter: 562
num_labels: 16
batch_size: 16
eval_batch_size: 16
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 3.0
num_heads: 3
use_agreement_apm: True
apm_percentile: 0.05
multihead_apm_variant: v4
no_low: False
apm_disagreement_weight: 3
threshold_algo: freematch
apm_cutoff: 0.0
smoothness: 0.997
uratio: 1
use_cat: False
optim: AdamW
lr: 0.00001
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: longformer_base_multihead
net_from_name: False
data_dir: ./data
dataset: aegis2.0_RH_eda
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
max_length: 1024
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: 0
text_weak_aug: eda_synonym
text_strong_aug: eda_full
load_labeled: True