algorithm: multihead_apm
net: vit_small_patch2_32
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth

# optimization configs
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
lr: 0.0005
layer_decay: 0.5
optim: AdamW
# maybe we can delete them
weight_decay: 0.0005
momentum: 0.9
ema_m: 0.0

# other configs
use_cat: True
amp: False
clip: 0.0
use_tensorboard: True
use_wandb: False

# dataset configs
dataset: cifar100
img_size: 32
num_labels: 400
num_classes: 100
crop_ratio: 0.875
net_from_name: False
data_dir: ./data
train_sampler: RandomSampler

# algorithm specific configs
hard_label: True
uratio: 1
ulb_loss_ratio: 1.0
use_agreement_apm: True
apm_percentile: 0.05
hard_label: True
seed: 0

# device configs
gpu: 0
world_size: 1
num_workers: 2
distributed: False

# test configs
save_dir: ./saved_models/usb_cv/multihead_apm/
save_name: agree_5_cifar100_200
overwrite: False