algorithm: marginmatch
save_dir: ./saved_models/usb_llm_safety/marginmatch
save_name: marginmatch_wildguard_RH_2000_paraphrase_mistral_2_aug_seed_2
resume: True
load_path: ./saved_models/usb_llm_safety/marginmatch/marginmatch_wildguard_RH_2000_paraphrase_mistral_2_aug_seed_2/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 1
num_train_iter: 50000
num_warmup_iter: 500
num_log_iter: 125
num_eval_iter: 500
num_labels: 2000
batch_size: 4
eval_batch_size: 4
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
# #
threshold_algo: flexmatch
apm_cutoff: 0.0
smoothness: 0.997
# ###
uratio: 3
use_cat: False
optim: AdamW
lr: 0.00005
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: deberta_v3_base
net_from_name: False
data_dir: ./data
dataset: aegis2.0_RH_eda
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
max_length: 1024
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10013
dist_backend: nccl
gpu: 0
include_lb_to_ulb: False
text_weak_aug: orig
text_strong_aug: translated
save_pseudolabels_stats: True
