algorithm: multimatch
save_dir: ./saved_models/usb_llm_safety/multimatch
save_name: multimatch_wildguard_PH_2000_translate_deberta_seed_1_paraphrase_mistral_1_llama_2
resume: True
load_path: ./saved_models/usb_llm_safety/multimatch/multimatch_wildguard_PH_2000_translate_deberta_seed_1_paraphrase_mistral_1_llama_2/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 1
num_train_iter: 12500
num_warmup_iter: 125
num_log_iter: 31
num_eval_iter: 125
num_labels: 2000
batch_size: 16
eval_batch_size: 16
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
num_heads: 3
use_agreement_apm: True
apm_percentile: 0.05
multihead_apm_variant: v4
no_low: False
apm_disagreement_weight: 3
threshold_algo: freematch
apm_cutoff: 0.0
smoothness: 0.997
uratio: 1
use_cat: False
optim: AdamW
lr: 5.0e-05
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: deberta_v3_base_multihead
net_from_name: False
data_dir: ./data
dataset: aegis2.0_PH_eda_2
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
max_length: 512
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: 0
text_weak_aug: eda_synonym
text_strong_aug: eda_full
