algorithm: fixmatch
net: vit_tiny_patch2_32
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_tiny_patch2_32_mlp_im_1k_32.pth

# optimization configs
epoch: 1  
num_train_iter: 10 
num_eval_iter: 5   
num_log_iter: 5    
optim: AdamW
lr: 0.0005
layer_decay: 0.5
batch_size: 16
eval_batch_size: 16

# dataset configs
dataset: disaster
task: humanitarian
num_labels: 40
crop_ratio: 0.875
train_filename: train.jsonl
dev_filename: dev.jsonl
test_filename: test.jsonl
unlabeled_filename: unlabeled_eda.jsonl
data_dir: C:\\Users\\Robert_Popovici\\Desktop\\licenta\\datasets\\humanitarian_orig
img_dir: C:\\Users\\Robert_Popovici\\Desktop\\licenta\\datasets

# algorithm specific configs
hard_label: True
uratio: 2
ulb_loss_ratio: 1.0

# device configs
gpu: None
world_size: 1
num_workers: 2
distributed: False