algorithm: marginmatch_mmbt_bert

# optimization configs
epoch: 1
num_train_iter: 1000 
num_eval_iter: 1000   
num_log_iter: 1    
optim: AdamW
lr: 0.00001
layer_decay: 0.5
batch_size: 2
eval_batch_size: 4

# dataset configs
dataset: disaster
task: humanitarian
num_labels: 40
crop_ratio: 0.875
train_filename: train_eda.jsonl
dev_filename: dev_eda.jsonl
test_filename: test_eda.jsonl
unlabeled_filename: unlabeled_eda.jsonl
data_dir: C:\\Users\\Robert_Popovici\\Desktop\\licenta\\datasets\\humanitarian
img_dir: C:\\Users\\Robert_Popovici\\Desktop\\licenta\\datasets
weak_text_tag: eda_02
strong_text_tag: back_translate

# algorithm specific configs
hard_label: True
uratio: 2
ulb_loss_ratio: 1.0

# device configs
gpu: None
world_size: 1
num_workers: 2
distributed: False