algorithm: fixmatch_multihead
save_dir: ./saved_models/usb_nlp/multihead_cotraining_abc_imb
save_name: multihead_cotraining_abc_aclImdb_imb100_2
resume: True
load_path: ./saved_models/usb_nlp/multihead_cotraining_abc_imb/multihead_cotraining_abc_aclImdb_imb100_2/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 102400
num_warmup_iter: 5120
num_log_iter: 256
num_eval_iter: 2048
num_labels: 1000
lb_imb_ratio: 100
ulb_imb_ratio: 100
ulb_num_labels: 10000
batch_size: 8
eval_batch_size: 8
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
use_head_cutoff: False
num_heads: 3
adjust_clf_size: False
imb_algorithm: abc
abc_p_cutoff: 0.95
abc_loss_ratio: 1.0
uratio: 1
use_cat: False
optim: AdamW
lr: 0.00005
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: bert_base_uncased_multihead
net_from_name: False
data_dir: ./data
dataset: aclImdb
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
max_length: 512
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10003
dist_backend: nccl
gpu: 0
